baseURL = "https://mooc-accessibility.inria.fr/"
languageCode = "fr-fr"
title = "Inria MOOC Accessibility"
disableKinds = ["taxonomy", "taxonomyTerm", "sitemap"]
enableGitInfo = true

[mediaTypes]
  [mediaTypes."text/embed"]
    suffixes = ["html"]

[outputFormats]
  [outputFormats.EMBED]
    baseName = "embed"
    suffix = "html"
    mediaType = "text/embed"

[outputs]
  home = ["HTML"]
  page = ["HTML", "EMBED"]

[params]
mediaBaseURL = "https://static.bordeaux.inria.fr/mooc-accessibility/media"
