baseURL = "http://qlf-mooc-accessibility.bordeaux.inria.fr/"
languageCode = "fr-fr"
title = "Inria MOOC Accessibility"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "sitemap"]

[mediaTypes]
  [mediaTypes."text/fun"]
    suffixes = ["html"]

[outputFormats]
  [outputFormats.FUN]
    baseName = "fun"
    suffix = "html"
    mediaType = "text/fun"

[outputs]
  home = ["HTML"]
  page = ["HTML", "FUN"]

[params]
mediaBaseURL = "https://static.bordeaux.inria.fr/mooc-accessibility/media"
